name: Java CI with Maven
on:
  push:
    branches: [ 'main', 'master' ]
  pull_request:
    branches: [ 'main', 'master' ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # ✅ Correct SemVer format
          distribution: 'temurin'
      - name: Maven Package
        run: mvn -B clean package  # ✅ Use 'mvn', not 'run'
      - name: Maven Verify
        run: mvn -B clean verify   # ✅ Use 'mvn', not 'run'